### PR TITLE
WRQ-8596: Adapt performanceMetrics app for Agate performance tests

### PR DESCRIPTION
**Pull request by daniel-stoian-lgp**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Adapted performanceMetrics app for Agate performance tests

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Adapted performanceMetrics app for Agate performance tests
Note: I reverted some changes from the testResults file made in #77 in order to keep the same file structure on the server where the results are stored. This was affecting reading of data from the performance metrics app

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
this PR is for creating the graph app.

In #79, we created the necesary tests for Agate components. Now they can be run via jenkins and the test results are saved on the enact server.

In this user story, I adapted the graph app to also handle the test results of Agate performance tests, together with the Sandstone ones.

In order to review it, it must be ran locally, To do that properly, please download the  attached file "public.zip" (in the user story) and extract it in the local "performanceMetrics" folder, then run the app with "enact serve". If it looks ok, then the code can be merged.

After it is merged, I will create a packed version fo the graph app and someone in Enact SWP will put it on the enact server, just like it was done in the past

### Links
[//]: # (Related issues, references)
WRQ-8596

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

### CODE REVIEW

**Review by adrian-cocoara-lgp — APPROVED** [review]
LGTM 👍

**Comment by seunghoh** [comment]
@daniel-stoian-lgp Would you please update more details in the PR description? I might miss the history of the agate perf. app. I have a missing the history since the PR https://github.com/enactjs/performance-tests/pull/79 
Thanks

**Review by seunghoh — CHANGES_REQUESTED** [review]
@daniel-stoian-lgp Thank you so much for your detailed information. It helped me to review it. 
These are some minor requests
1. Chart title. "Sandstone Performance Metrics" -> "Enact Performance Metrics"
2. Chart X label shows "Sandstone Version" even change the Theme "Agate"
3. How about making "Overview" page just like Sandstone? 

Please fix 1 and 2 and I will merge.
It's up to you to add 3 in this PR or make a separate user story.

**Review by seunghoh — APPROVED** [review]
LGTM

**Pull request merged**
